---

- tags:
    - setup-all
    - setup-system-swap
    - install-all
    - install-system-swap
  block:
    - name: Run swap installation tasks
      when: system_swap_enabled | bool
      ignore_errors: "{{ system_swap_ignore_errors }}"
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- tags:
    - setup-all
    - setup-system-swap
  block:
    - name: Run swap uninstallation tasks
      when: not system_swap_enabled | bool
      ignore_errors: "{{ system_swap_ignore_errors }}"
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
